# IBM i Connection Details
ibmi.host=IOHANA
ibmi.user=IPGUI
ibmi.password=IPGUI

file.member.monitor.enabled=true
files.members.to.monitor=IPTSFILI,IPPOHDR,IPPOHDR,2000;IPTSFILI,IPPOHDR,PENDING,150
monitor.interval.ms=300000
metrics.port=8601
client.name=IOHANA
logo.path=..\..\logo\IPLogo.jpg
