# IBM i Connection Details
ibmi.host=10.110.25.20
ibmi.user=IPGUI
ibmi.password=IPGUI
client.name=MACC

# Message Filtering Criteria (comma-separated values)
job.failure.message.ids=CPA0702,CPF0001
job.failure.keywords=ENDED ABNORMALLY

# Monitor Interval (in milliseconds) - How often the monitor checks the queue
monitor.interval.ms=60000

# Port for Prometheus metrics server
metrics.port=3019
