# IBM i Connection Details
ibmi.host=10.197.42.108
ibmi.user=IPGUI
ibmi.password=IPGUI

# List of Jobs to monitor
# Format: jobName,jobUser[,expectedSubsystem];jobName2,jobUser2[,expectedSubsystem2];...
# The expectedSubsystem is optional. If not provided, it will search across all subsystems.
jobs.list=IPMSGQ,IPTS,IPTS;QBATCH,QSYS;IP009330,IPTS;IP008501,IPTS;IP009340,IPTS;CHK_RECVR,IPTS;DCORLS,IPTS;DOSFRR,IPTS;DXUIDBI,IPTS;DBOCVT,IPTS

# Monitoring interval in seconds
monitor.pollingIntervalSeconds=60

# Port for Prometheus metrics exporter (e.g., 9092 for Jobs)
prometheus.port=5137
