# IBM i Connection Details
ibmi.host=IOHANA
ibmi.user=IPGUI
ibmi.password=IPGUI

# List of job queue IDs to monitor, comma-separated
# Each ID should then have its own set of properties (name, library, threshold)
jobqueue.monitor.ids=jobq1,jobq2,jobq3,jobq4

# Configuration for Q1
jobqueue.jobq1.name=QBATCH
jobqueue.jobq1.library=QGPL
jobqueue.jobq1.threshold=15

# Configuration for 'interactive_jobq' (Example: If you had another job queue like QINTER in QCPL)
jobqueue.jobq2.name=QINTER
jobqueue.jobq2.library=QGPL
jobqueue.jobq2.threshold=0

jobqueue.jobq3.name=QSNADS
jobqueue.jobq3.library=QGPL
jobqueue.jobq3.threshold=15

jobqueue.jobq4.name=QSPL
jobqueue.jobq4.library=QGPL
jobqueue.jobq4.threshold=15


client.monitor=IOHANA



# Monitor Settings
monitor.interval.ms=60000
metrics.port=3031