#error.folder=\\\\SMARTRETAIL6\\Error
metrics.port=4041
monitor.interval.ms=30000

ibmi.server=192.168.9.121
ibmi.user=IPGUI
ibmi.password= IPGUI
client.name=IOHANA

monitor.location.IPTSFIL8_DLX_DISTRO_errors.path=//192.168.9.121/root/IPTSFIL8/WI/DLX/DISTRO
monitor.location.IPTSFIL8_DLX_DISTRO_errors.types=XML

monitor.location.IPTSFIL8_OMNI_EXPORT_errors.path=//192.168.9.121/root/OCS/IPTSFIL8/EXPORT/ERRORS
monitor.location.IPTSFIL8_OMNI_EXPORT_errors.types=TXT

monitor.location.IPTSFIL8_DXUIDBI_errors.path=//192.168.9.121/root/IPJAVA/IPDIRECT/IPDSFIL8/DXUIDBI/errors
monitor.location.IPTSFIL8_DXUIDBI_errors.types=XML

monitor.location.IPTSFIL8_MACC_ONESTOCK_errors.path=//192.168.9.121/root/MONSOON_ACCESSORIZE8/IMPORT/ONESTOCK/ERROR
monitor.location.IPTSFIL8_MACC_ONESTOCK_errors.types=csv
