# Configuration for Server Downtime Monitor
exporter.port=3014
ping.interval.seconds=10

# List of servers to monitor (comma-separated IP addresses or hostnames)
servers.list=IPQA-AUTO2,IPQA-AUTO,IPDEMO-APP2,IN-PLANNING2,IP-HYBRID,IWEB,IWEB2,SMARTRETAIL2,SMARTRETAIL3,SMARTRETAIL4,SMARTRETAIL5,SMARTRETAIL6,IOHANA,IONO,ILUAU