# IBM i Connection Details
ibmi.host=192.168.9.121
ibmi.user=IPGUI
ibmi.password=IPGUI
client.name=IOHANA



# List of critical subsystem names to monitor for status changes, comma-separated
# Example: QCTL,QINTER,QSPL,QBATCH
subsystem.critical.names=QBASE,QBATCH
ibmi.system.context.library=QSYS

# Monitor Settings
# Interval in milliseconds for checking metrics (e.g., 60000ms = 1 minute)
monitor.interval.ms=60000
metrics.port=3015
